# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(400, 120)
        About.setMinimumSize(QtCore.QSize(400, 120))
        About.setMaximumSize(QtCore.QSize(400, 120))
        self.label = QtWidgets.QLabel(About)
        self.label.setGeometry(QtCore.QRect(10, 20, 300, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.ButtonOk = QtWidgets.QPushButton(About)
        self.ButtonOk.setGeometry(QtCore.QRect(160, 90, 75, 23))
        self.ButtonOk.setObjectName("ButtonOk")
        self.label_2 = QtWidgets.QLabel(About)
        self.label_2.setGeometry(QtCore.QRect(30, 45, 281, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(About)
        self.label_3.setGeometry(QtCore.QRect(30, 65, 281, 16))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(About)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "About"))
        self.label.setText(_translate("About", "About Resistor Calculator 0.1 (02.02.2023)"))
        self.ButtonOk.setText(_translate("About", "OK"))
        self.label_2.setText(_translate("About", "Copyright © 2022-2022 by Stepan Toshel."))
        self.label_3.setText(_translate("About", "Program for calculating the resistance of electrical circuits."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    About = QtWidgets.QDialog()
    ui = Ui_About()
    ui.setupUi(About)
    About.show()
    sys.exit(app.exec_())
