# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ResistorCalculator(object):
    def setupUi(self, ResistorCalculator):
        ResistorCalculator.setObjectName("ResistorCalculator")
        ResistorCalculator.resize(800, 200)
        ResistorCalculator.setMinimumSize(QtCore.QSize(800, 200))
        ResistorCalculator.setMaximumSize(QtCore.QSize(800, 200))
        self.gridLayoutWidget = QtWidgets.QWidget(ResistorCalculator)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-1, 19, 801, 62))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem3, 3, 1, 1, 1)
        self.ResistFormula = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ResistFormula.setMinimumSize(QtCore.QSize(700, 30))
        self.ResistFormula.setMaximumSize(QtCore.QSize(700, 30))
        self.ResistFormula.setStyleSheet("QPushButton {\n"
"    border-radius: 8px; \n"
"}")
        self.ResistFormula.setObjectName("ResistFormula")
        self.gridLayout.addWidget(self.ResistFormula, 2, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(ResistorCalculator)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 140, 801, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.ButtonCalculate = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ButtonCalculate.setMinimumSize(QtCore.QSize(200, 30))
        self.ButtonCalculate.setStyleSheet("QPushButton {\n"
"    background-color:  rgb(0, 160, 255);\n"
"    color:  rgb(240, 240, 240);\n"
"    border-radius: 8px; \n"
"}")
        self.ButtonCalculate.setObjectName("ButtonCalculate")
        self.horizontalLayout.addWidget(self.ButtonCalculate)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.TitleResult = QtWidgets.QLabel(ResistorCalculator)
        self.TitleResult.setGeometry(QtCore.QRect(50, 100, 50, 20))
        self.TitleResult.setMinimumSize(QtCore.QSize(50, 20))
        self.TitleResult.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.TitleResult.setFont(font)
        self.TitleResult.setObjectName("TitleResult")
        self.Result = QtWidgets.QLabel(ResistorCalculator)
        self.Result.setGeometry(QtCore.QRect(100, 100, 60, 16))
        self.Result.setText("")
        self.Result.setObjectName("Result")

        self.retranslateUi(ResistorCalculator)
        QtCore.QMetaObject.connectSlotsByName(ResistorCalculator)

    def retranslateUi(self, ResistorCalculator):
        _translate = QtCore.QCoreApplication.translate
        ResistorCalculator.setWindowTitle(_translate("ResistorCalculator", "Resistor Calculator"))
        self.ButtonCalculate.setText(_translate("ResistorCalculator", "Calculate"))
        self.TitleResult.setText(_translate("ResistorCalculator", "Result "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ResistorCalculator = QtWidgets.QDialog()
    ui = Ui_ResistorCalculator()
    ui.setupUi(ResistorCalculator)
    ResistorCalculator.show()
    sys.exit(app.exec())
